#!/bin/bash

### BEGIN INIT INFO
# Provides:          start_eureka
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Démarre les règles iptables
# Description:       Charge la configuration du pare-feu iptables
### END INIT INFO

java -jar /etc/eureka/eureka-1.jar

start()
{
     # Mettez ici le démarrage de votre programme
	echo "start"
	java -jar /etc/eureka/eureka-1.jar
}

stop()
{
     # Mettez ici un kill sur votre programme
	echo "stop"
}

restart()
{
    stop;
    sleep 1;
    start;
}
case $1 in
start) 
      start;;
stop)
      stop;;
restart)
      restart;;
*)
      start;;
esac

