version:  "2"
services:
  api-gateway:
    build: ./api-gateway
    depends_on:
      - config-server
    command: ["./etc/api-gateway/wait-for-config-server.sh", "config-server:8001", "--","java","-jar","/etc/api-gateway/api-gateway-1.jar","FOREGROUND"]
    ports: 
      - "8080:8080"
    networks:
      front:
        ipv4_address: 172.18.100.12

  eureka:
    # ports:
    #   - "8010:8010"
    build: ./eureka
    networks:
      front:
        ipv4_address: 172.18.100.10 

  config-server:
    build: ./config-server
    # ports:
    #   - "8001:8001"
    networks:
      front:
        ipv4_address: 172.18.100.11 

 

  # rabbitmq:
  #   image: rabbitmq
  #   networks:
  #     - front

  # sentence-gateway:
  #   build: ./sentence-gateway
  #   networks:
  #     - back

  # word:
  #   build: ./word
  #   networks: 
  #     - back

  # challenge:
  #   build: ./challenge
  #   networks: 
  #    - back

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.100.0/16
        - gateway: 172.18.100.1

  # back:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 172.19.0.0/16
  #       - gatway: 172.19.0.1
