version:  "2"
services:
  api-gateway:
    build: ./microservices/api-gateway
    depends_on:
      - sentence-gateway
    command: ["./etc/api-gateway/wait-for-config-server.sh", "sentence-gateway:8020", "--","mvn","spring-boot:run","FOREGROUND"]
    ports: 
      - "8080:8080"
    networks:
      front:
        ipv4_address: 172.18.100.12

  eureka:
    # ports:
    #   - "8010:8010"
    build: ./microservices/eureka
    networks:
      front:
        ipv4_address: 172.18.100.10 

  config-server:
    build: ./microservices/config-server
    # ports:
    #   - "8001:8001"
    networks:
      front:
        ipv4_address: 172.18.100.11 

 

  # rabbitmq:
  #   image: rabbitmq
  #   networks:
  #     - front

  sentence-gateway:
    build: ./microservices/sentence-gateway
    depends_on:
      - config-server
    command: ["./etc/sentence-gateway/wait-for-config-server.sh", "config-server:8001", "--","mvn","spring-boot:run","FOREGROUND"]
    networks:
      #- back
      front:
        ipv4_address: 172.18.100.15

  word:
    build: ./microservices/word
    depends_on:
      - config-server
    command: ["./etc/word/wait-for-config-server.sh", "config-server:8001", "--","java","-jar","/etc/word/word-1.jar","--spring.profiles.active=subject","FOREGROUND"]

    networks: 
      #- back
      - front

  challenge:
    build: ./microservices/challenge
    depends_on:
      - config-server
    command: ["./etc/challenge/wait-for-config-server.sh", "config-server:8001", "--","java","-jar","mvn","spring-boot:run","FOREGROUND"]

    networks: 
     #- back
      front:
        ipv4_address: 172.18.100.16

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.100.0/16
          gateway: 172.18.100.1

  # back:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 172.19.100.0/16
  #       - gateway: 172.19.100.1
